### ISSUE TITLE
C300: Setup the development environment

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#655]
## Use Case:

1.0

## Tasks:

- [ ] [M] add the main command
- [ ] [M] make the session reboot
- [ ] [M] give it the ability to setup a master password
- [ ] [M] reset the master password
- [ ] [M] change main configuration settings

**Comment by idancali** [comment]
done without the master password reset for now
